// <auto-generated />
using FabricShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FabricShop.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20191113164505_trying")]
    partial class trying
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FabricShop.Data.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeliveryDistance");

                    b.Property<string>("DeliveryTime");

                    b.Property<string>("OrderType");

                    b.Property<string>("ProductCode");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FabricShop.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cate1");

                    b.Property<string>("Cate2");

                    b.Property<string>("Cate3");

                    b.Property<string>("Color");

                    b.Property<string>("Composition");

                    b.Property<string>("ProductId");

                    b.Property<string>("ProductName");

                    b.Property<string>("VendorName");

                    b.Property<string>("Weave");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
